config/routes.rb
Rails.application.routes.draw do
  # change default devise path from 'users/action_name'
  # to '/action_name'
  devise_for :users, path: ''

  # Or it's possible to change default devise path only for specific endpoints
  # as :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  # end

  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  resources :relationships

  get 'account', to: 'relationships#show'
  # post 'account/add_friend', to: 'relationships#add_friend'


  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  mount_uploader :image, ImageUploader

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true,
                    length: { minimum: 5 }

  validates_processing_of :image
  validate :image_size_validation
  
  private
  def image_size_validation
    errors[:image] << 'The image size should be less then 1Mb' if image.size > 1.megabytes
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :user_one, class_name: 'User'
  belongs_to :user_two, class_name: 'User' 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles

  has_many :relationships_1, class_name: 'Relationship', foreign_key: :user_one_id
  has_many :relationships_2, class_name: 'Relationship', foreign_key: :user_two_id

  has_many :friends_1, through: :relationships_1, class_name: 'User', source: :user_two
  has_many :friends_2, through: :relationships_2, class_name: 'User', source: :user_one

  def friends
    friends_1 + friends_2
  end

  private :friends_1, :'friends_1=', :friends_2, :'friends_2='

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  # http_basic_authenticate_with name: "vetalshev", 
  #                              password: "Password01", 
  #                              except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params.merge(user_id: current_user.id))

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :image, :remove_image)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "vetalshev", 
                               password: "Password01", 
                               only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :authenticate_user!

  def create
    @relation = Relationship.new(user_one_id: current_user.id, user_two_id: params[:user_id])
    respond_to do |format|
      if @relation.save
        new_friend = User.find(params[:user_id])
        format.json { 
          render json: new_friend, status: :created, location: @relation
        }
      else
        format.json {
          render json: @relation.errors, status: :unprocessable_entity
        }
      end
    end
  end

  def destroy
    @relation = Relationship.where(user_one_id: current_user.id, user_two_id: params[:id]).first

    respond_to do |format|
      if @relation.destroy
        friend = User.find(params[:id])
        format.json { 
          render json: friend, status: :created, location: @relation
        }
      else
        format.json {
          render json: @relation.errors, status: :unprocessable_entity
        }
      end
    end
  end

  def show
    # TODO: Check and refactor the next:
    # the next line should return a list of posts created by current user
    # current_user.articles
    @articles = Article.where(user_id: current_user.id)
    @possible_friends = User.all - [current_user] - current_user.friends
  end

end
  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li style="color: red;"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.label :image %><br/>
    <%= form.file_field :image %>
  </p>
  <% if form.object.image? %>
    <%= image_tag(form.object.image.thumb.url, alt: 'Image') %>
    <p>
      <%= form.check_box :remove_image %>
      <%= form.label :remove_image %>
    </p>
  <% end %>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Thumbnail</th>
    <th>Title</th>
    <th>Text</th>
    <th>Actions</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td>
        <%= image_tag(article.image.thumb.url, alt: 'Image') if article.image? %>
      </td>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td>
        <%= link_to 'Show', article_path(article) %>
        <% if user_signed_in? %>
          <%= link_to 'Edit', edit_article_path(article) %>
          <%= link_to 'Destroy', article_path(article),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% if user_signed_in? %>
  <%= link_to 'New article', new_article_path %>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Author:</strong>
  <%= @article.user_id %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <%= image_tag(@article.image.url, alt: 'Image') if @article.image? %>
</p>

<% if user_signed_in? %>
  <%= link_to 'Destroy', article_path(@article),
      method: :delete,
      data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <%= render @article.comments %>
<% end %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

<hr/>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to 'Home', welcome_index_path %> |
        <%= link_to 'Articles', articles_path %> |
        <% if user_signed_in? %>
          <%= link_to 'New article', new_article_path %> |
          <%= link_to 'My account', account_path %> |
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %> 
        <% else %>
          <%= link_to 'Sign in', new_user_session_path %> |
          <%= link_to 'Sign up', new_user_registration_path %>
        <% end %>
      </nav>
    </header>
    
    <article class="container">
      <%= yield %>
    </article>

    <footer>
      &copy;&nbsp;Copyright
    </footer>

  </body>
</html>

app/views/relationships/show.html.erb
<h1>
  Hello, <%= current_user.email %>
</h1>

<% if @possible_friends.length > 0 %>
  <h2>Are you familiar?</h2>
  <ul>
    <% @possible_friends.each do |possible_friend| %>
      <li>
        <p><%= possible_friend.email %></p>
        <button type="button" 
                class="add-friend-btn"
                data-user-id="<%= possible_friend.id %>">
          Add to friends
        </button>
      </li>
    <% end %>
  </ul>
<% end %>

<h2>My friends:</h2>
<ul>
  <% current_user.friends.each do |friend| %>
    <li>
      <p><%= friend.email %></p>
      <button type="button" 
              class="delete-friend-btn"
              data-user-id="<%= friend.id %>">
        Remove from friends
      </button>
    </li>
  <% end %>
  <% if current_user.friends.length == 0 %>
    Currently you dont have friends
  <% end %>
</ul>

<h2>My articles:</h2>

<ol>
  <% @articles.each do |article| %>
    <li>
      <%= image_tag(article.image.thumb.url, alt: 'Image') if article.image? %>
      <%= article.title %>
    </li>
  <% end %>
  <% if @articles.length == 0 %>
    Currently you dont have any articles
  <% end %>
</ol>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>